#!/usr/bin/env bash

function deploy() {
	nixos-rebuild $1 --flake .#default --target-host admin@lebesgue --use-remote-sudo --verbose
}

nix flake common

if [[ -n $1 ]]; then 
	deploy $1
else
	deploy "switch"
fi

